name: Docs check - Ubuntu

on:
  push:
    paths:
    - 'include/**'
    - 'docs/**'
    - 'docs_check/**'
    - '.github/workflows/noarr_docs_check_ubuntu.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install gcc
      run: sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install g++ clang

    - name: Test
      run: docs_check/check
